server:
  port: 8099

spring:
#  profiles:
#    active: local
  application:
    name: kafka4

  kafka:
    template:
      default-topic: file-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sixthsense?serverTimezone=Asia/Seoul
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update

    devtools:
      restart:
        enable: true

logging:
  level:
    package com.example.kafka4.client: DEBUG

---
server:
  port: 8099
spring:
  profiles: publish

  kafka:
    template:
      default-topic: file-events
    producer:
      bootstrap-servers: 59.29.224.136:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10

  application:
    name: kafka-producer-service

  datasource:
    url: jdbc:mysql://mysql:3306/k8sdb?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: k8suser
    password: k8suser
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true


  main:
    allow-bean-definition-overriding: true

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true